<a href="https://colab.research.google.com/github/ojasvi-1705/Applied-Machine-Learning/blob/main/Numpy_Ques_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

_____
**Write a program to create an array [10, 5, 7, 20, 15, -9, 33], print it, Find the maximum and minimum Value of the array**

In [ ]:
array = [10,5, 7, 20 , 15, -9, 33]
print(array)
print(max(array))
print(min(array))


[10, 5, 7, 20, 15, -9, 33]
33
-9


___
**Write a program to accept two matrices [[1,2],[3,4]],   [[2,4],[6,8]]and find the sum and subtraction of two matrices**

In [ ]:
#code here
matrix1 = [[1,2],[3,4]]
matrix2 = [[2,4], [6,8]]

#sum of two matrices
sum_matrix = [[0,0],[0,0]]
for i in range(len(matrix1)):
  for j in range(len(matrix1[0])):
    sum_matrix[i][j] = matrix[i][j] + matrix2[i][j]
    print(sum_matrix)






[[np.int64(6), 0], [0, 0]]
[[np.int64(6), np.int64(4)], [0, 0]]
[[np.int64(6), np.int64(4)], [np.int64(12), 0]]
[[np.int64(6), np.int64(4)], [np.int64(12), np.int64(11)]]


In [ ]:
matrix1 = [[1,2],[3,4]]
matrix2 = [[2,4], [6,8]]

def add_matrices(mat1, mat2):
    if len(mat1) != len(mat2) or len(mat1[0]) != len(mat2[0]):
        return "Matrices must have the same dimensions for addition."
    result = [[0 for _ in range(len(mat1[0]))] for _ in range(len(mat1))]
    for i in range(len(mat1)):
        for j in range(len(mat1[0])):
            result[i][j] = mat1[i][j] + mat2[i][j]
    return result

print("Matrix 1:", matrix1)
print("Matrix 2:", matrix2)

sum_matrix = add_matrices(matrix1, matrix2)
print("Sum of matrices:", sum_matrix)

______
**Write a program to accept an array of elements and find the maximum without using max function**

In [ ]:
#Code here
array = [10, 5, 7, 20, 15, -9, 33]

if not array:
  print("array not provided")
else:
  max_num = array[0]
  for element in array[1:]:
    if element > max_num:
      max_num = element
  print(f"My array is {array}")
  print(f"Maximum number in array is {max_num}")

My array is [10, 5, 7, 20, 15, -9, 33]
Maximum in array is 33


___
**Write a program to generate a ranodom matrix of size 5 X 6. Add another row containing random elements to it. Find the sum of each row.**

In [ ]:
#Code here
import numpy as np
rows = 5
cols = 6
lower_bound = 0
upper_bound = 9
matrix = np.random.randint(lower_bound, upper_bound, (rows, cols))
print(f"{matrix} \n")
new_random_row = np.random.randint(lower_bound, upper_bound, size=cols)
print(f"new added row is {new_random_row}")
matrix_with_random_row = np.vstack((matrix, new_random_row))
print(f"\n{matrix_with_random_row}")

row_sums = np.sum(matrix_with_random_row, axis=1)
print("\n sum of each row ")
print(row_sums)


[[7 0 5 4 6 4]
 [2 7 3 4 8 2]
 [6 1 3 0 6 3]
 [0 4 8 3 4 7]
 [3 8 7 1 2 3]] 

new added row is [2 2 0 7 1 0]

[[7 0 5 4 6 4]
 [2 7 3 4 8 2]
 [6 1 3 0 6 3]
 [0 4 8 3 4 7]
 [3 8 7 1 2 3]
 [2 2 0 7 1 0]]

 sum of each row 
[26 26 19 26 24 12]


___
**Write a program to generate a ranodm integer matrix of size 5 X 6. Add another column containing random integers to it. Compute the sine of each element and print it**

In [ ]:
#Code here
import numpy as np
rows = 5
cols = 6
lower_bound = 0
upper_bound = 9
matrix = np.random.randint(lower_bound, upper_bound, (rows, cols))
print(f"{matrix} \n")
new_random_col = np.random.randint(lower_bound, upper_bound, size=(rows,1))
print(f"new added column is {new_random_col}")
matrix_with_random_col = np.hstack((matrix, new_random_col))
print(f"\n{matrix_with_random_col}")

col_sums = np.sum(matrix_with_random_col, axis=0)
print("\n sum of each col ")
print(col_sums)



[[2 1 1 3 1 2]
 [8 4 1 8 3 7]
 [7 7 0 7 0 8]
 [0 6 1 1 4 2]
 [8 6 0 7 6 2]] 

new added column is [[4]
 [5]
 [3]
 [4]
 [7]]

[[2 1 1 3 1 2 4]
 [8 4 1 8 3 7 5]
 [7 7 0 7 0 8 3]
 [0 6 1 1 4 2 4]
 [8 6 0 7 6 2 7]]

 sum of each col 
[25 24  3 26 14 21 23]


___
**Write a program to generate a ranodm matrix of size 5 X 6. Consider the 3rd and 4th row; and 2nd, 3rd and 4th column and print the resultant matrix using slicing**

In [ ]:
#Code here
import numpy as np
rows = 5
cols = 6
lower_bound = 0
upper_bound = 9
matrix = np.random.randint(lower_bound, upper_bound, (rows, cols))
print(f"{matrix}\n")
sliced_matrix = matrix[2:4, 1:4]
print(f"sliced matrix is {sliced_matrix}")


[[4 0 8 1 8 8]
 [6 3 0 4 7 6]
 [4 4 7 8 3 6]
 [6 2 3 7 5 3]
 [5 3 0 5 3 5]]

sliced matrix is [[4 7 8]
 [2 3 7]]


### Great Job!